-- Create payments table

CREATE TYPE payment_type_enum AS ENUM ('Bank Transfer', 'Cash');


CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id uuid NOT NULL REFERENCES public.subscriptions(id),
  user_id uuid NOT NULL REFERENCES public.users(id),
  added_by uuid REFERENCES auth.users(id),
  amount numeric NOT NULL,
  payment_type payment_type_enum NOT NULL DEFAULT 'Bank Transfer',
  payment_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin access" ON payments
FOR ALL TO authenticated
USING (is_admin());

CREATE POLICY "Allow staff access" ON payments
FOR ALL TO authenticated
USING (is_staff());
