-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
CREATE TYPE subscription_status AS ENUM (
  'Advance Received',
  'Paper Collected',
  'Documents Ready',
  'Completed'
);

CREATE TYPE rubber_stamp_status AS ENUM (
  'Not Available',
  'Available',
  'With Client'
);

CREATE TYPE signatory_type AS ENUM (
  'company',
  'individual'
);

CREATE TYPE file_type AS ENUM (
  'other',
);


CREATE TABLE admin_users (
  user_id uuid NOT NULL,
  role text DEFAULT 'admin'::text,
  CONSTRAINT admin_users_pkey PRIMARY KEY (user_id),
  CONSTRAINT admin_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  price numeric,
  features jsonb,
  status boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  tag text,
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);

CREATE TABLE suite_numbers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  suite_number text NOT NULL UNIQUE,
  status text DEFAULT 'available'::text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT suite_numbers_pkey PRIMARY KEY (id)
);
CREATE TABLE users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text,
  email text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  plan_id uuid,
  purchased_date date,
  start_date date,
  expiry_date date,
  purchase_amount numeric,
  received_amount numeric,
  status subscription_status DEFAULT 'Advance Received',
  suite_number text,
  rubber_stamp rubber_stamp_status DEFAULT 'Not Available',
  signatory_type signatory_type,
  created_at timestamp without time zone DEFAULT now(),
  name_board text DEFAULT 'Not Available'::text CHECK (name_board = ANY (ARRAY['Not Available'::text, 'Available'::text])),
  activities text[] DEFAULT '{}'::text[],
  br_pdf_url text,
  br_doc_url text,
  ll_pdf_url text,
  ll_doc_url text,
  drive_folder_url text,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);

CREATE TABLE subscription_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL UNIQUE,
  name text,
  cin text,
  pan text,
  tan text,
  address text,
  created_at timestamp without time zone DEFAULT now(),
  coi_file_path text,
  coi_file_name text,
  CONSTRAINT subscription_companies_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_companies_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE subscription_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL,
  label file_type NOT NULL,
  file_name text NOT NULL,
  file_path text NOT NULL,
  mime_type text,
  file_size_bytes bigint,
  uploaded_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  extracted_data jsonb,
  CONSTRAINT subscription_files_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_files_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE subscription_signatories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL UNIQUE,
  name text,
  designation text,
  aadhaar_number text,
  address text,
  created_at timestamp without time zone DEFAULT now(),
  aadhaar_file_path text,
  aadhaar_file_name text,
  CONSTRAINT subscription_signatories_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_signatories_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE subscription_status_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid,
  old_status subscription_status,
  new_status subscription_status NOT NULL,
  changed_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT subscription_status_logs_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_status_logs_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT subscription_status_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.admin_users(user_id)
);


-- Create payments table

CREATE TYPE payment_type_enum AS ENUM ('Bank Transfer', 'Cash');


CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id uuid NOT NULL REFERENCES public.subscriptions(id),
  user_id uuid NOT NULL REFERENCES public.users(id),
  added_by uuid REFERENCES auth.users(id),
  amount numeric NOT NULL,
  payment_type payment_type_enum NOT NULL DEFAULT 'Bank Transfer',
  payment_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin access" ON payments
FOR ALL TO authenticated
USING (is_admin());

CREATE POLICY "Allow staff access" ON payments
FOR ALL TO authenticated
USING (is_staff());

